@startuml
skinparam defaultFontName Courier 10 Pitch
class CharFrame{
	-flag: String
	-type: String
	-num: String
	-data: String
	-crc: String

	/'the idea is for the constructor to immediately convert fields to
	easier to work with bit strings'/
	+CharFrame(type:char, num:char, data:String)
	+getFlag():String
	+getType():char
	+setType(type:char)
	+getNum():int
	+setNum(num:char)
	+getData():String
	+setData(data:String)
	{static} +bitStuffed(str:String):String
	+computeCRC():String
	+format():String
}
class CheckSumCalculator{
	+computeCRC(bitstring:String)
	+validate(bitstring:String, crc:String):boolean
}
class FrameFileReader{

	+openFile(filename: String, flag:String):boolean
	+closeFile()
	+getNextFrame():CharFrame

}
class CLI{
	+startREPL()
}
class Test{
	+runTests()
}
class Receiver{
	+listen(port:int)
}
class Sender{
	-sentFrames:String[8]/'needed to resend'/

	+send(machine:String, port:int, filename:String)
	+send(machine:String, port:int, frame:CharFrame)
}
FrameFileReader ..> CharFrame
CharFrame --> CheckSumCalculator
CLI  --> "0..1" Sender
CLI --> "0..1" Receiver
CLI --> "0..1" Test
Sender --> FrameFileReader
Sender ..> CharFrame
Receiver ..> CharFrame
@enduml
